### ISSUE TITLE
Error if template helper is not a function

### ISSUE THREAD

**Issue by maxnowack** [kadirahq/meteor-debug#1]
Kadira debug crashes the rendering process, if there is a template helpers wich isn't a function.
I don't know why someone should do this, but in Blaze it's possible.

Code: https://github.com/meteorhacks/kadira-debug/blob/master/lib/client/providers/blaze.js#L32-L44

**Comment by arunoda** [comment]
Okay good point. I'll do a fix now.

**Comment by arunoda** [comment]
Fixed and released :)

**Comment by maxnowack** [comment]
Wow, that was fast! Thank you! :)

**Comment by maxnowack** [comment]
I've discovered that the helper comes from the `alethes:pages` package and unfortunately, the fix doesn't work for me.
Is it possible for you to return `fn` if it's isn't a function?
I tried it locally and it works great.

**Comment by arunoda** [comment]
Yep. That's right. Could you send me a PR?

**Comment by maxnowack** [comment]
sure!
Should I increment the version?

**Comment by arunoda** [comment]
Thanks. Don't increment versions. I'm writing some tests now. 
After that, I'll do a release.

**Comment by arunoda** [comment]
See: https://github.com/meteorhacks/kadira-debug/pull/2#issuecomment-111718663
