### ISSUE TITLE
Not able to add the package to the app

### ISSUE THREAD

**Issue by kampta** [kadirahq/meteor-debug#28]
It is giving the following error:

=> Errors while adding packages:

While downloading kadira:debug@3.0.1...:
error: getaddrinfo ENOTFOUND

While downloading kadira:runtime-dev@0.0.1...:
error: getaddrinfo ENOTFOUND

While downloading meteorhacks:kadira@2.23.4...:
error: getaddrinfo ENOTFOUND

While downloading meteorhacks:meteorx@1.3.1...:
error: getaddrinfo ENOTFOUND

**Comment by arunoda** [comment]
Could you check your internet? This seems like your machine can't reach Meteor's package server.
