### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by brucejo75** [kadirahq/meteor-debug#40]
I have been a meteor user since February.  The interface descriptions I see look very good and useful.

At one point early on the package seemed to work and give me debug info.  However, it has seemed to degrade regularly.

It has degraded to the point now where I am getting nothing at all today.  See [#26](https://github.com/kadirahq/meteor-debug/issues/26).  I just tried running it against the simple app that `meteor create` produces and the package has a build error.

The issues have stacked up and I do not see any activity.

Is there a debug alternative?

**Comment by JSzaszvari** [comment]
Yes. Gone.
