### ISSUE TITLE
MITM attacker can replace http://debug.kadiraio.com with code that exfiltrates app data

### ISSUE THREAD

**Issue by mattmccutchen** [kadirahq/meteor-debug#45]
The [FAQ](https://kadira.io/platform/kadira-debug/faq#why-isn-t-kadira-debug-ui-using-https-) claims that Kadira Debug is secure even though it is served from http://debug.kadiraio.com (without HTTPS) because data from the app isn't sent anywhere.  Of course, this claim assumes that the user has received the legitimate Kadira Debug UI.  A MITM attacker could substitute a modified version of the Kadira Debug UI that sends the data to his own server.  The problem is analogous to the more familiar one of [a login form served without HTTPS](https://developer.mozilla.org/en-US/docs/Web/Security/Insecure_passwords#Serving_the_login_form_over_HTTP).

One idea for a fix is to use a route on the app as the entry point (e.g., http://localhost:3000/kadira-debug) and have that route load the scripts and resources for the Kadira Debug UI from an HTTPS server.  There should be no browser restrictions on non-HTTPS pages loading HTTPS resources.

**Comment by arunoda** [comment]
That's a good suggestion but Kadira Debug is no longer support with recent Meteor versions.
