### ISSUE TITLE
Firefox Connection Input Text Invisible

### ISSUE THREAD

**Issue by iDoMeteor** [kadirahq/meteor-debug#5]
When attempting to use the connection input field in Firefox (36.0.4, Linux), nothing is displayed.  It works, just cannot see what you type.

**Comment by arunoda** [comment]
hmm. 
Hey sorry. I didn't follow what you are saying.
Could you clarify a bit more?

**Comment by arunoda** [comment]
Okay got it ;)

**Comment by iDoMeteor** [comment]
Another awesome product though :)

**Comment by arunoda** [comment]
Thanks.

**Comment by arunoda** [comment]
We fixed this issue and now you'll be able to use FF with Kadira Debug.

**Comment by iDoMeteor** [comment]
Confirmed, +1

**Comment by arunoda** [comment]
thanks.
