### ISSUE TITLE
Only Works When Loaded with Chrome

### ISSUE THREAD

**Issue by iDoMeteor** [kadirahq/meteor-debug#6]
Dashboard does display in FF (once I figured out I had to load the site in Chrome), though not as nicely.  However, it took me about 30-40 mins to figure out that I had to use Chrome to load the application before I got a connection, Firefox does not connect although it does work just fine with the main Kadira.io app.

**Comment by arunoda** [comment]
I hope this is related to #5.
It seems like we are having an issue in FF. This works pretty well with Chrome and Safari.
Will fix it.

**Comment by arunoda** [comment]
I hope the new release will fix this. (`v1.3.2`)

**Comment by iDoMeteor** [comment]
Will try it

**Comment by iDoMeteor** [comment]
Confirmed, +1
